In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[1.7753e+28, 7.0744e+31, 7.5011e+28],
        [1.2680e-14, 1.8888e+31, 1.2712e+31],
        [3.2745e-12, 1.4583e-19, 1.8888e+31],
        [1.9421e+20, 4.9567e+28, 1.4353e-19],
        [2.7530e+12, 7.5338e+28, 7.6286e-19]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.4886, 0.4681, 0.3629],
        [0.3757, 0.0424, 0.5810],
        [0.6877, 0.9757, 0.0182],
        [0.6122, 0.4119, 0.0749],
        [0.0575, 0.5481, 0.0941]])


In [5]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.rand_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.6909, 0.7048, 0.0494],
        [0.3523, 0.2683, 0.8137],
        [0.3819, 0.2928, 0.5953],
        [0.1951, 0.8795, 0.6114],
        [0.7243, 0.2775, 0.7215]])
torch.Size([5, 3])


In [16]:
y = torch.rand(5,3)
print(x+y)
print(torch.add(x, y))

tensor([[1.6675, 1.2140, 0.0671],
        [1.1478, 0.4082, 1.1596],
        [0.7877, 1.1019, 0.8363],
        [1.0164, 1.1254, 1.1563],
        [1.2005, 0.9074, 1.2939]])
tensor([[1.6675, 1.2140, 0.0671],
        [1.1478, 0.4082, 1.1596],
        [0.7877, 1.1019, 0.8363],
        [1.0164, 1.1254, 1.1563],
        [1.2005, 0.9074, 1.2939]])


In [18]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.6675, 1.2140, 0.0671],
        [1.1478, 0.4082, 1.1596],
        [0.7877, 1.1019, 0.8363],
        [1.0164, 1.1254, 1.1563],
        [1.2005, 0.9074, 1.2939]])


In [20]:
y.add_(x)
print(y)
print(x[:,1])

tensor([[2.3584, 1.9189, 0.1165],
        [1.5001, 0.6764, 1.9734],
        [1.1696, 1.3947, 1.4317],
        [1.2116, 2.0049, 1.7677],
        [1.9248, 1.1849, 2.0154]])
tensor([0.7048, 0.2683, 0.2928, 0.8795, 0.2775])


In [22]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [25]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1799])
1.1799074411392212


In [27]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [29]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [30]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
