In [65]:
import torch
x = torch.ones(2,2)
print(x)
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [66]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [67]:
z = y * y * 3
out = z.mean() # 所有元素的均值
print(z, out)
print("------------")
print(z) 
print(out) # out包含单个标量

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)
------------
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


In [68]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [69]:
# out.backward() # 在这里和out.backward(torch.tensor(1.))效果一样
out.backward(torch.tensor(1.))
print(x.grad)
# print(y.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([1439.7104,   60.0051,  416.8658], grad_fn=<MulBackward0>)


In [15]:
v = torch.tensor([0.1, 1.0, 0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [17]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
