In [31]:
import torch
x = torch.ones(2,2)
print(x)
x = torch.ones(2,2, requires_grad=True)
print(x)
print(x.grad_fn)
# grad_fn是执行操作的过程中得到的一个参数，如果用户自己新建的变量，则grad_fn的取值为None
# grad_fn表示的是各种操作（加减乘除、求均值、求和等）
# x = x * 2
# print(x)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [32]:
y = x + 2
print(y)
print(y.grad_fn)
w = y - 1
print(w)
print(w.grad_fn) # 

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<SubBackward0>)


In [33]:
z = y * y * 3
out = z.mean() # 所有元素的均值
print(z, out)
print("------------")
print(z) 
print(out) # out包含单个标量

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)
------------
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


In [34]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [35]:
# out.backward() # 在这里和out.backward(torch.tensor(1.))效果一样
out.backward(torch.tensor(1.))
print(x.grad)
# print(y.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [36]:
x = torch.randn(3, requires_grad=True)
y = x * 2
print(x)
# https://stackoverflow.com/questions/50753477/what-does-data-norm-1000-do-in-pytorch
# data.norm是基本的l2范数
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([0.9613, 0.0702, 0.1116], requires_grad=True)
tensor([1968.8187,  143.8361,  228.5327], grad_fn=<MulBackward0>)


In [37]:
v = torch.tensor([0.1, 1.0, 0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [17]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [27]:
# l2范数data.norm()
a = torch.randn(3, requires_grad=True)
b = a * 2
print(b.data)
print(b.data.norm())
print(torch.pow(b,2))
print(torch.sum(torch.pow(b, 2)))
print(torch.sqrt(torch.sum(torch.pow(b, 2))))


tensor([-1.4673,  0.7257,  0.3235])
tensor(1.6686)
tensor([2.1530, 0.5266, 0.1047], grad_fn=<PowBackward0>)
tensor(2.7843, grad_fn=<SumBackward0>)
tensor(1.6686, grad_fn=<SqrtBackward>)
